apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
      containers:
      - image: mysql:5.7
        name: mysql
        ports:
        - containerPort: 3306
        envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: mysql-config
        # env:
        # - name: MYSQL_ROOT_PASSWORD
        #   value: R1234r
        # - name: MYSQL_PASSWORD
        #   value: Clarusway_1
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_USER
        #   value: clarus

        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pv-storage
      
      
        resources: {}