apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: polatdocker/webserver
        name: webserver
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: server-config
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
          # value: Clarusway_1
        # - name: MYSQL_DATABASE_HOST
        #   value: mysql
        # - name: MYSQL_DATABASE
        #   value: phonebook
        # - name: MYSQL_USER
        #   value: clarus
          
        resources: {}
